#!/bin/bash
#shellcheck disable=SC2034

set -o errexit
set -o pipefail
set -o xtrace

# Define useful variables
LIB_DIRNAME=MIaS/target/lib
JAR_FILENAME=MIaS/target/MIaS-"$IMAGE_TAG"-SNAPSHOT.jar
IMAGE_TAG=miratmu/mias:"$IMAGE_TAG"

set -o nounset

# Define command aliases
docker_build() {
  docker build --build-arg LIB_DIRNAME="$LIB_DIRNAME" --build-arg JAR_FILENAME="$JAR_FILENAME" --compress --no-cache --force-rm --squash -t "$IMAGE_TAG" "$@"
  docker tag "$IMAGE_TAG" miratmu/mias:latest
}

docker_push() {
  docker push "$IMAGE_TAG"
  docker push miratmu/mias:latest
}

mias() {
  docker run -v "$(readlink -f "$1")":/dataset:ro -v "$(readlink -f "$2")":/index:rw \
    --rm "$IMAGE_TAG"
}
